### ISSUE TITLE
Week 2 Review Ticket

### ISSUE THREAD

**Issue by TANAY101405** [KoolKidKai/Siuuuu#24]
- [x] [Project Owner / Sponsor presentation(visuals like wireframes or HTML pages), results of review, PII concerns, hosting plan, and software license](https://koolkidkai.github.io/Siuuuu/presentation)

- [x] [1st Code in GitHub with software license per 5.5]()

**Comment by jm1021** [comment]
Siuuu group.   Talked about GitHub page to contain information of plans.  Code Learning site associated with Hack Club.  

Wireframes talk about drop down and advancing through levels.  Point system and awards.  Talked about embedding Replit.   

Features needed calendar and roster.   These would help run the people in the club.  Shared HTML pages.  

Discussed target audience of Freshmen and Sophmore.  

Shared project planning with boxes.   In this shared database design and other technicals.

Shared User Experience diagram.  But did not discuss.  Looked promising.

Went over PII but did not personalize it much to my understanding.

Great question about Replit?   Needs investigation.

**Comment by BrianZhang2016** [comment]
Sponsor: Hackclub
Log in and link account
Can link to replit account
Different levels: Awarded points
Calendar that shows off plans
Balance website between enjoyable and mature
MIT Licence

Might add:
Leaderboard to keep track of scores. 
Hide calendar from people who wont use it

Question: 
How does replit link to your website to "get rewards"?

**Comment by NathanManangan** [comment]
Siuuu -
Sponsor: Hack Club
Plans:
- Website plans to be certain levels of learning where you can earn points, with a store and link it into an account.
- Used to be focused on Ronaldo (SIUUUU), but reduced to be more focused on code and technicals.
- Calendar and roster page for important dates for the club.
- Directly embed Repilt and Replit account link
- Target audience: Freshmen and Sophmores, making it more user friendly and make the site less repetitive.
- Wireframes and diagrams are sophisticated
- License : MIT, to ensure page is totally

Suggestions:
- For points store maybe add change of backgrounds or a profile picture thats changeable
- Leaderboard (Ranked by points, as mentioned)
- Daily Task
- Calendar ( Who can post, who can view )

**Comment by PunarvasuS** [comment]
Great Idea you guys have here! It has use outside of just for a grade or just for the club. You can even make it into some type of wordle clone if you simplify it enough.
Look into having a built in IDE rather than logging in with replit

**Comment by Pitsco** [comment]
- Contacts: Recieve feedback
- Current Plans: A code learning based website (sponsored by the hack club @ Del Norte)
- point system for completing code tasks 
- Link replit account, you can code in the website
- Include more technical diagrams
- MIT Software License (Just a school project, not trying to make money off of it)
- Integration of Replit?
- Points virtual or related to the club?

**Comment by byronlu06** [comment]
Siuuuuu
Sponsor: Hack Club
Improvements made:
- Reduce a focus on Ronaldo because unprofessional
- Revamping wireframes to show professional website for club
- Include more info on technical plans

Plans:
- Website is going to be multiple levels: beginner intermediate, and advanced
- When you complete a given problem in code, you will be awarded points
- Balance sophisticated professional website with something that targets freshmen and sophomores
- User friendly and easier and not to make the website too repetitive
- Something that really brings in people and makes them wanna learn more code
- Link to Replit account to allow code in website itself
- Continue working on calendar and roster page
- Login to store points in account

Suggestions:
- Allow users to interact with others while learning code
- Integrate a daily task to ensure users are learning actively

**Comment by lordpotash** [comment]
Great Idea you guys have here! It has use outside of just for a grade or just for the club. You can even make it into some type of wordle clone if you simplify it enough.
Look into having a built in IDE rather than logging in with replit (you will have to deal with replit log in details and keeping them safe)
I'm not so sure on having a built in calendar, you can just use google calendar and invite everyone to a group. The positives of a built in calendar are that a user will be able to see _only_ Hack Club meetings/events
Along with a calendar you should add a page that has general meeting times, as well as the room. Just info about the club, if you haven't already. 

Make sure to have your website be somewhat accessible to non-HackClub members, it will help with recruitment of new members. Hack Club can convert the link into a QR code and put it on those pamphlets hanging around the hallways.
